---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-15.10
  - name: ubuntu-1404
  - name: fedora-23

suites:
  - name: default
    run_list:
      - recipe[ts3::default]
